baseURL = "https://lht97.github.io/"
title = "Haitian LI"
languageCode = "en-us"
paginate = "10"
theme = "mainroad"

[[menus.main]]
name = "Home"
url = "/"
weight = 1

[[menus.main]]
name = "Resume"
url = "/documents/cv.pdf"
weight = 2

[params]
description = "Haitian LI's personal website"
mainSections = []
mathjax = true
post_meta = ["author", "date", "categories", "translations"]

[params.logo]
image = "img/li.jpg"
title = "Haitian LI"
subtitle = "PhD Candidate"

[params.sidebar]
home = "right"
list = "right"
single = "right"
widgets = ["recent", "categories", "taglist", "social", "languages"]

[params.style.vars]
highlightColor = "#016064"

[params.thumbnail]
visibility = ["list"]

[params.widgets]
recent_num = 3

[params.widgets.social]
github = "lht97"
email = "hai-tian.li@connect.polyu.hk"

[[params.widgets.social.custom]]
title = "ORCID"
url = "https://orcid.org/0000-0002-9477-1222"
icon = "svg/orcid.svg"


