baseURL = 'https://lht97.github.io/'
languageCode = 'en-us'
title = 'Haitian LI'
theme = 'mainroad'

[Params.logo]
  image = 'img/li.jpg'
  title = 'Haitian LI'
  subtitle = 'PhD Candidate'

[Params.style.vars]
  highlightColor = '#016064'

[[menus.main]]
name = "Home"
url = "/"
weight = 1

[[menus.main]]
name = "Resume"
url = "documents/cv.pdf"
weight = 2

[[menus.main]]
name = "Project"
url = "/"
weight = 3

[params.widgets]
recent_num = 5

[[params.widgets.social.custom]]
title = "hai-tian.li@polyu.edu.hk"
url = "mailto:tom.ragonneau@polyu.edu.hk"
icon = "svg/email.svg"

[[params.widgets.social.custom]]
title = "GitHub"
url = "https://github.com/lht97"
icon = "svg/github.svg"

[[params.widgets.social.custom]]
title = "ORCID"
url = "https://orcid.org/0000-0003-2717-2876"
icon = "svg/orcid.svg"

